version: '2'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=tsuro
      - POSTGRES_PASSWORD=tsuro
      - POSTGRES_PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
