# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170214_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='turn',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
