# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_play_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='first_score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='second_score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
